In [1]:
# Modules
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
Podcast_df = pd.read_csv('Data/train.csv')

In [3]:
Podcast_df

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
0,0,Mystery Matters,Episode 98,NaN,True Crime,74.81,Thursday,Night,NaN,0.0,Positive,31.41998
1,1,Joke Junction,Episode 26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative,88.01241
2,2,Study Sessions,Episode 16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative,44.92531
3,3,Digital Digest,Episode 45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive,46.27824
4,4,Mind & Body,Episode 86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral,75.61031
...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,Learning Lab,Episode 25,75.66,Education,69.36,Saturday,Morning,NaN,0.0,Negative,56.87058
749996,749996,Business Briefs,Episode 21,75.75,Business,35.21,Saturday,Night,NaN,2.0,Neutral,45.46242
749997,749997,Lifestyle Lounge,Episode 51,30.98,Lifestyle,78.58,Thursday,Morning,84.89,0.0,Negative,15.26000
749998,749998,Style Guide,Episode 47,108.98,Lifestyle,45.39,Thursday,Morning,93.27,0.0,Negative,100.72939
749999,749999,Sports Central,Episode 99,24.10,Sports,22.45,Saturday,Night,36.72,0.0,Neutral,11.94439

In [4]:
Podcast_df.columns

Index(['id', 'Podcast_Name', 'Episode_Title', 'Episode_Length_minutes',
       'Genre', 'Host_Popularity_percentage', 'Publication_Day',
       'Publication_Time', 'Guest_Popularity_percentage', 'Number_of_Ads',
       'Episode_Sentiment', 'Listening_Time_minutes'],
      dtype='object')

In [5]:
Podcast_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 12 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           750000 non-null  int64
 1   Podcast_Name                 750000 non-null  object
 2   Episode_Title                750000 non-null  object
 3   Episode_Length_minutes       662907 non-null  float64
 4   Genre                        750000 non-null  object
 5   Host_Popularity_percentage   750000 non-null  float64
 6   Publication_Day              750000 non-null  object
 7   Publication_Time             750000 non-null  object
 8   Guest_Popularity_percentage  603970 non-null  float64
 9   Number_of_Ads                749999 non-null  float64
 10  Episode_Sentiment            750000 non-null  object
 11  Listening_Time_minutes       750000 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 68.7+ MB

In [6]:
Podcast_df.describe()

,id,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,750000.000000,662907.000000,750000.000000,603970.000000,749999.000000,750000.000000
mean,374999.500000,64.504738,59.859901,52.236449,1.348855,45.437406
std,216506.495284,32.969603,22.873098,28.451241,1.151130,27.138306
min,0.000000,0.000000,1.300000,0.000000,0.000000,0.000000
25%,187499.750000,35.730000,39.410000,28.380000,0.000000,23.178350
50%,374999.500000,63.840000,60.050000,53.580000,1.000000,43.379460
75%,562499.250000,94.070000,79.530000,76.600000,2.000000,64.811580
max,749999.000000,325.240000,119.460000,119.910000,103.910000,119.970000

In [7]:
Podcast_df['Podcast_Name'].value_counts()

Podcast_Name
Tech Talks             22847
Sports Weekly          20053
Funny Folks            19635
Tech Trends            19549
Fitness First          19488
Business Insights      19480
Style Guide            19364
Game Day               19272
Melody Mix             18889
Criminal Minds         17735
Finance Focus          17628
Detective Diaries      17452
Crime Chronicles       17374
Athlete's Arena        17327
Fashion Forward        17280
Tune Time              17254
Business Briefs        17012
Lifestyle Lounge       16661
True Crime Stories     16373
Sports Central         16191
Digital Digest         16171
Humor Hub              16144
Mystery Matters        16002
Comedy Corner          15927
Joke Junction          15074
Wellness Wave          15009
Sport Spot             14778
Gadget Geek            14770
Home & Living          14686
Laugh Line             14673
Life Lessons           14464
World Watch            14043
Sound Waves            13928
Global News            13649
Mind & Body            13639
Daily Digest           13391
Money Matters          13380
Current Affairs        13138
Market Masters         13092
Study Sessions         13053
Innovators             12913
Music Matters          12652
Learning Lab           12291
Educational Nuggets    12245
Healthy Living         12198
Brain Boost            11543
Health Hour            11114
News Roundup            9169
Name: count, dtype: int64

In [8]:
Podcast_df['Episode_Sentiment'].value_counts(dropna=False)

Episode_Sentiment
Neutral     251291
Negative    250116
Positive    248593
Name: count, dtype: int64

In [9]:
Podcast_df['Number_of_Ads'].value_counts(dropna=False)

Number_of_Ads
0.00      217592
1.00      214069
3.00      160173
2.00      158156
103.25         2
53.37          1
NaN            1
103.91         1
103.00         1
53.42          1
103.75         1
12.00          1
103.88         1
Name: count, dtype: int64

In [10]:
Podcast_df[Podcast_df['Number_of_Ads'] ==103.25]

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
602553,602553,Sound Waves,Episode 53,112.27,Music,28.19,Tuesday,Morning,23.15,103.25,Neutral,103.12686
672139,672139,Sound Waves,Episode 35,115.74,Music,28.95,Tuesday,Afternoon,23.50,103.25,Neutral,103.12686

In [11]:
Podcast_df['Genre'].value_counts(dropna=False)

Genre
Sports        87606
Technology    86256
True Crime    85059
Lifestyle     82461
Comedy        81453
Business      80521
Health        71416
News          63385
Music         62743
Education     49100
Name: count, dtype: int64

In [12]:
  Podcast_df['Episode_Length_minutes'].value_counts(dropna=False)

Episode_Length_minutes
NaN          87093
6.600000       925
34.400000      617
30.690000      576
31.680000      533
             ...
14.498053        1
8.115479         1
93.660301        1
98.298620        1
62.167294        1
Name: count, Length: 12269, dtype: int64

In [13]:
Podcast_Test_df['Episode_Length_minutes'].value_counts(dropna=False)

NameError: name 'Podcast_Test_df' is not defined

In [ ]:
Podcast_Test_df = pd.read_csv('Data/test.csv')
Podcast_Test_df

In [ ]:
Podcast_Test_df['Publication_Day'].value_counts(dropna=False)

In [ ]:
Podcast_Test_df['Publication_Time'].value_counts(dropna=False)

In [14]:
Podcast_df[Podcast_df['Episode_Length_minutes'].isna()]

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
0,0,Mystery Matters,Episode 98,NaN,True Crime,74.81,Thursday,Night,NaN,0.0,Positive,31.41998
9,9,Music Matters,Episode 81,NaN,Music,82.18,Thursday,Night,59.72,3.0,Neutral,45.94761
29,29,Health Hour,Episode 38,NaN,Health,45.97,Saturday,Evening,15.43,1.0,Negative,25.38384
43,43,Funny Folks,Episode 93,NaN,Comedy,33.02,Saturday,Afternoon,64.70,2.0,Positive,35.11072
49,49,Style Guide,Episode 75,NaN,Lifestyle,78.82,Saturday,Morning,NaN,2.0,Positive,24.40379
...,...,...,...,...,...,...,...,...,...,...,...,...
749926,749926,Current Affairs,Episode 48,NaN,News,78.14,Thursday,Afternoon,50.88,3.0,Positive,14.67000
749936,749936,Melody Mix,Episode 7,NaN,Music,29.15,Sunday,Afternoon,NaN,0.0,Negative,47.79899
749943,749943,World Watch,Episode 42,NaN,News,80.46,Saturday,Afternoon,15.18,1.0,Neutral,80.42861
749954,749954,Life Lessons,Episode 54,NaN,Lifestyle,59.31,Tuesday,Night,44.94,2.0,Neutral,99.33292
749984,749984,Game Day,Episode 13,NaN,Sports,70.22,Tuesday,Evening,53.74,1.0,Positive,37.26790

In [15]:
Null_df = Podcast_df[Podcast_df['Episode_Length_minutes'].isna()]

In [16]:
Null_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87093 entries, 0 to 749984
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           87093 non-null  int64
 1   Podcast_Name                 87093 non-null  object
 2   Episode_Title                87093 non-null  object
 3   Episode_Length_minutes       0 non-null      float64
 4   Genre                        87093 non-null  object
 5   Host_Popularity_percentage   87093 non-null  float64
 6   Publication_Day              87093 non-null  object
 7   Publication_Time             87093 non-null  object
 8   Guest_Popularity_percentage  64921 non-null  float64
 9   Number_of_Ads                87093 non-null  float64
 10  Episode_Sentiment            87093 non-null  object
 11  Listening_Time_minutes       87093 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 8.6+ MB

In [17]:
notnull_df = Podcast_df[Podcast_df['Episode_Length_minutes'].notna()]
notnull_df

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
1,1,Joke Junction,Episode 26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative,88.01241
2,2,Study Sessions,Episode 16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative,44.92531
3,3,Digital Digest,Episode 45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive,46.27824
4,4,Mind & Body,Episode 86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral,75.61031
5,5,Fitness First,Episode 19,26.54,Health,48.96,Saturday,Afternoon,NaN,3.0,Positive,22.77047
...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,Learning Lab,Episode 25,75.66,Education,69.36,Saturday,Morning,NaN,0.0,Negative,56.87058
749996,749996,Business Briefs,Episode 21,75.75,Business,35.21,Saturday,Night,NaN,2.0,Neutral,45.46242
749997,749997,Lifestyle Lounge,Episode 51,30.98,Lifestyle,78.58,Thursday,Morning,84.89,0.0,Negative,15.26000
749998,749998,Style Guide,Episode 47,108.98,Lifestyle,45.39,Thursday,Morning,93.27,0.0,Negative,100.72939
749999,749999,Sports Central,Episode 99,24.10,Sports,22.45,Saturday,Night,36.72,0.0,Neutral,11.94439

# Results

*  750,000 rows in the training and 250,000 in the test.
*  12 categories, six categorical, six numerical.
*  linear regression.
*  around 10% of the category

In [ ]:
len(Podcast_df['Podcast_Name'].value_counts())

In [18]:
# Study of the length of programs
Prog_Tech_Talks = Podcast_df[Podcast_df['Podcast_Name'] == 'Tech Talks']

In [19]:
Prog_Tech_Talks

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
15,15,Tech Talks,Episode 47,68.33,Technology,75.33,Thursday,Evening,92.90,0.0,Neutral,63.97718
90,90,Tech Talks,Episode 30,68.44,Technology,63.55,Thursday,Evening,29.12,0.0,Negative,62.51000
123,123,Tech Talks,Episode 12,82.96,Technology,54.33,Wednesday,Night,6.18,1.0,Neutral,67.36443
146,146,Tech Talks,Episode 64,86.83,Technology,69.61,Thursday,Night,58.89,1.0,Neutral,49.88000
226,226,Tech Talks,Episode 29,112.75,Technology,48.35,Tuesday,Night,58.77,3.0,Negative,98.15000
...,...,...,...,...,...,...,...,...,...,...,...,...
749945,749945,Tech Talks,Episode 87,111.14,Technology,74.88,Monday,Night,88.88,3.0,Neutral,62.27626
749968,749968,Tech Talks,Episode 26,38.79,Technology,52.36,Wednesday,Afternoon,NaN,0.0,Neutral,16.61857
749970,749970,Tech Talks,Episode 92,39.46,Technology,73.46,Tuesday,Evening,46.41,2.0,Positive,30.95658
749974,749974,Tech Talks,Episode 94,57.39,Technology,40.66,Wednesday,Night,91.44,3.0,Negative,40.97805
749975,749975,Tech Talks,Episode 9,78.97,Technology,49.24,Sunday,Afternoon,86.10,2.0,Negative,56.03675

In [20]:
Prog_Tech_Talks[Prog_Tech_Talks['Publication_Time']=='Evening']

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
15,15,Tech Talks,Episode 47,68.33,Technology,75.33,Thursday,Evening,92.90,0.0,Neutral,63.97718
90,90,Tech Talks,Episode 30,68.44,Technology,63.55,Thursday,Evening,29.12,0.0,Negative,62.51000
273,273,Tech Talks,Episode 6,54.23,Technology,78.66,Sunday,Evening,NaN,0.0,Neutral,46.59939
894,894,Tech Talks,Episode 36,NaN,Technology,48.79,Saturday,Evening,71.42,2.0,Neutral,71.75507
989,989,Tech Talks,Episode 5,84.71,Technology,60.79,Monday,Evening,85.67,1.0,Neutral,44.22934
...,...,...,...,...,...,...,...,...,...,...,...,...
749537,749537,Tech Talks,Episode 70,10.16,Technology,47.12,Tuesday,Evening,64.64,3.0,Neutral,6.94000
749545,749545,Tech Talks,Episode 52,34.91,Technology,98.31,Saturday,Evening,47.95,2.0,Negative,21.49845
749714,749714,Tech Talks,Episode 98,35.81,Technology,95.63,Saturday,Evening,88.19,3.0,Negative,32.77623
749916,749916,Tech Talks,Episode 36,46.79,Technology,24.18,Monday,Evening,NaN,0.0,Positive,38.79078
749970,749970,Tech Talks,Episode 92,39.46,Technology,73.46,Tuesday,Evening,46.41,2.0,Positive,30.95658

In [21]:
Prog_Tech_Talks[Prog_Tech_Talks['Publication_Time']=='Evening'].describe()

,id,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,5739.000000,5019.000000,5739.000000,4483.000000,5739.000000,5739.000000
mean,377675.233664,64.043179,60.041359,51.463453,1.382819,45.974082
std,216531.770400,32.369293,23.370866,28.775868,1.110483,27.546621
min,15.000000,1.480000,20.010000,0.010000,0.000000,0.000000
25%,193940.000000,37.305000,38.490000,27.420000,0.000000,24.244445
50%,377863.000000,61.680000,60.720000,52.660000,1.000000,42.894310
75%,567671.500000,93.350000,80.700000,76.600000,2.000000,63.967990
max,749970.000000,119.990000,99.980000,99.890000,3.000000,119.780000

In [22]:
Prog_Tech_Talks[Prog_Tech_Talks['Publication_Time']=='Afternoon'].describe()

,id,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,5542.000000,4857.000000,5542.000000,4407.000000,5542.000000,5542.000000
mean,375475.065319,63.604045,58.952463,51.634418,1.348971,45.620909
std,214174.452165,33.602721,22.674644,28.098730,1.088992,28.421130
min,294.000000,5.010000,20.010000,0.060000,0.000000,0.000000
25%,190297.000000,34.490000,38.640000,28.245000,0.000000,22.199380
50%,373875.500000,62.270000,58.940000,52.450000,1.000000,43.413260
75%,561402.500000,94.080000,78.562500,75.665000,2.000000,65.102205
max,749975.000000,119.990000,99.880000,99.980000,3.000000,119.790000

In [23]:
Prog_Tech_Talks[Prog_Tech_Talks['Publication_Time']=='Night'].describe()

,id,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,6092.000000,5410.000000,6092.000000,4837.000000,6092.000000,6092.000000
mean,375983.358175,66.345885,59.612178,52.025971,1.348326,47.966409
std,216291.900388,32.924595,22.975143,28.648071,1.098861,27.911779
min,123.000000,5.090000,20.010000,0.040000,0.000000,0.000000
25%,189782.500000,39.085000,38.730000,28.230000,0.000000,25.452343
50%,375845.500000,65.070000,59.340000,52.230000,1.000000,45.875790
75%,565104.750000,96.580000,79.442500,77.710000,2.000000,67.211443
max,749974.000000,119.950000,99.960000,99.990000,3.000000,119.560000

In [24]:
Prog_Tech_Talks[Prog_Tech_Talks['Publication_Time']=='Morning'].describe()

,id,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,5474.000000,4804.000000,5474.000000,4386.000000,5474.000000,5474.000000
mean,370688.010047,63.000357,59.017801,52.371265,1.352941,44.887120
std,216390.251564,33.444458,22.830447,27.614456,1.091311,28.429025
min,266.000000,5.050000,20.090000,0.040000,0.000000,0.000000
25%,183506.000000,33.900000,38.437500,30.360000,0.000000,21.443290
50%,369234.500000,60.080000,59.220000,52.015000,1.000000,40.507535
75%,557598.250000,94.185000,78.557500,74.940000,2.000000,65.661260
max,749923.000000,120.320000,109.380000,99.970000,3.000000,119.900000