In [2]:
# Modules
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# Load DataFrames
Podcast_Train_df = pd.read_csv('Data/train.csv')
Podcast_Test_df = pd.read_csv('Data/test.csv')

In [4]:
Podcast_Train_df

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
0,0,Mystery Matters,Episode 98,NaN,True Crime,74.81,Thursday,Night,NaN,0.0,Positive,31.41998
1,1,Joke Junction,Episode 26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative,88.01241
2,2,Study Sessions,Episode 16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative,44.92531
3,3,Digital Digest,Episode 45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive,46.27824
4,4,Mind & Body,Episode 86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral,75.61031
...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,Learning Lab,Episode 25,75.66,Education,69.36,Saturday,Morning,NaN,0.0,Negative,56.87058
749996,749996,Business Briefs,Episode 21,75.75,Business,35.21,Saturday,Night,NaN,2.0,Neutral,45.46242
749997,749997,Lifestyle Lounge,Episode 51,30.98,Lifestyle,78.58,Thursday,Morning,84.89,0.0,Negative,15.26000
749998,749998,Style Guide,Episode 47,108.98,Lifestyle,45.39,Thursday,Morning,93.27,0.0,Negative,100.72939
749999,749999,Sports Central,Episode 99,24.10,Sports,22.45,Saturday,Night,36.72,0.0,Neutral,11.94439

In [5]:
len(Podcast_Train_df['Podcast_Name'].value_counts())

48

In [6]:
len(Podcast_Test_df['Podcast_Name'].unique())

48

In [7]:
Podcast_Train_df['Podcast_Name'].unique()

array(['Mystery Matters', 'Joke Junction', 'Study Sessions',
       'Digital Digest', 'Mind & Body', 'Fitness First', 'Criminal Minds',
       'News Roundup', 'Daily Digest', 'Music Matters', 'Sports Central',
       'Melody Mix', 'Game Day', 'Gadget Geek', 'Global News',
       'Tech Talks', 'Sport Spot', 'Funny Folks', 'Sports Weekly',
       'Business Briefs', 'Tech Trends', 'Innovators', 'Health Hour',
       'Comedy Corner', 'Sound Waves', 'Brain Boost', "Athlete's Arena",
       'Wellness Wave', 'Style Guide', 'World Watch', 'Humor Hub',
       'Money Matters', 'Healthy Living', 'Home & Living',
       'Educational Nuggets', 'Market Masters', 'Learning Lab',
       'Lifestyle Lounge', 'Crime Chronicles', 'Detective Diaries',
       'Life Lessons', 'Current Affairs', 'Finance Focus', 'Laugh Line',
       'True Crime Stories', 'Business Insights', 'Fashion Forward',
       'Tune Time'], dtype=object)

In [8]:
len(Podcast_Train_df['Genre'].value_counts())

10

In [9]:
len(Podcast_Test_df['Genre'].value_counts())

10

In [10]:
Podcast_Train_df['Publication_Day'].unique()

array(['Thursday', 'Saturday', 'Tuesday', 'Monday', 'Sunday', 'Wednesday',
       'Friday'], dtype=object)

In [11]:
len(Podcast_Train_df['Publication_Day'].unique())

7

In [12]:
Podcast_Train_df['Publication_Time'].unique()

array(['Night', 'Afternoon', 'Evening', 'Morning'], dtype=object)

In [13]:
len(Podcast_Train_df['Publication_Time'].unique())

4

In [14]:
podcast_data = pd.DataFrame(columns=['Program','# progam','day','# week day','Time','# on that hour','mean','std'])

In [15]:
podcast_data

Empty DataFrame
Columns: [Program, # progam, day, # week day, Time, # on that hour, mean, std]
Index: []

In [16]:
# Pod_My_Ma[(Pod_My_Ma['Publication_Day']== 'Saturday') & (Pod_My_Ma['Publication_Time']== 'Morning')]['Episode_Length_minutes'].median()

In [17]:
n=0
for podcast in Podcast_Test_df['Podcast_Name'].unique():
    podname_df = Podcast_Train_df[Podcast_Train_df['Podcast_Name'] == podcast]
    feature = podcast
    program_num = len(podname_df)
    
    for day in podname_df['Publication_Day'].unique():
        pub_day_df = podname_df[podname_df['Publication_Day'] == day ]
        pod_day = day
        pod_day_num = len(pub_day_df)

        for hour in pub_day_df['Publication_Time'].unique():
            pub_hour_df = pub_day_df[pub_day_df['Publication_Time'] == hour ]
            time = hour
            time_num = len(pub_hour_df)
            mean = pub_hour_df['Episode_Length_minutes'].mean()
            std = pub_hour_df['Episode_Length_minutes'].std()
            podcast_data.loc[n] = [feature, program_num, pod_day, pod_day_num, time, time_num, mean, std]
            n = n +1
        n= n +4
    n=n +7

In [45]:
podcast_data

,Program,# progam,day,# week day,Time,# on that hour,mean,std
0,Educational Nuggets,12245,Monday,1753,Morning,400,63.721253,32.639350
1,Educational Nuggets,12245,Monday,1753,Evening,509,63.950889,32.486647
2,Educational Nuggets,12245,Monday,1753,Afternoon,410,66.523717,34.308373
3,Educational Nuggets,12245,Monday,1753,Night,434,66.025187,33.896819
8,Educational Nuggets,12245,Sunday,1870,Night,485,66.501642,31.548580
...,...,...,...,...,...,...,...,...
3004,News Roundup,9169,Monday,1393,Morning,310,59.708515,32.378594
3009,News Roundup,9169,Saturday,1260,Night,341,65.402736,33.064750
3010,News Roundup,9169,Saturday,1260,Morning,274,59.579551,33.594354
3011,News Roundup,9169,Saturday,1260,Evening,362,59.006311,33.696283
3012,News Roundup,9169,Saturday,1260,Afternoon,283,57.960421,32.611023

In [18]:
podcast_data.to_csv('Data/Podcast_data.csv', index=True)

In [19]:
podcast_data_order = pd.DataFrame(columns=['Program','# progam','day','# week day','Time','# in hour','mean','std'])

In [20]:
podcast_data_order

Empty DataFrame
Columns: [Program, # progam, day, # week day, Time, # in hour, mean, std]
Index: []

In [21]:
n=0
for podcast in Podcast_Test_df['Podcast_Name'].unique():
    podname_df = Podcast_Train_df[Podcast_Train_df['Podcast_Name'] == podcast]
    feature = podcast
    program_num = len(podname_df)
    
    for day in ['Sunday' ,'Monday' ,'Tuesday' ,'Wednesday','Thursday','Friday', 'Saturday']:
        try:
            pub_day_df = podname_df[podname_df['Publication_Day'] == day ]
            pod_day = day
            pod_day_num = len(pub_day_df)
        except:
            pub_day_df = podname_df
            pod_day = day
            pod_day_num = np.nan

        for hour in ['Night','Morning', 'Afternoon', 'Evening']:
            try:
                pub_hour_df = pub_day_df[pub_day_df['Publication_Time'] == hour ]
                time = hour
                time_num = len(pub_hour_df)
                mean = pub_hour_df['Episode_Length_minutes'].mean()
                std = pub_hour_df['Episode_Length_minutes'].std()
            except:
                pub_hour_df = pub_day_df
                time = hour
                time_num = np.nan
                mean = np.nan
                std = np.nan
                
            podcast_data_order.loc[n] = [feature, program_num, pod_day, pod_day_num, time, time_num, mean, std]
            n = n +1
        n= n +4
    n=n +7

In [50]:
podcast_data_order

,Program,# progam,day,# week day,Time,# in hour,mean,std
0,Educational Nuggets,12245,Sunday,1870,Night,485,66.501642,31.548580
1,Educational Nuggets,12245,Sunday,1870,Morning,411,63.443003,33.950159
2,Educational Nuggets,12245,Sunday,1870,Afternoon,431,65.855339,32.296243
3,Educational Nuggets,12245,Sunday,1870,Evening,543,63.491797,33.398955
8,Educational Nuggets,12245,Monday,1753,Night,434,66.025187,33.896819
...,...,...,...,...,...,...,...,...
3004,News Roundup,9169,Friday,1310,Evening,347,62.243377,34.413272
3009,News Roundup,9169,Saturday,1260,Night,341,65.402736,33.064750
3010,News Roundup,9169,Saturday,1260,Morning,274,59.579551,33.594354
3011,News Roundup,9169,Saturday,1260,Afternoon,283,57.960421,32.611023
3012,News Roundup,9169,Saturday,1260,Evening,362,59.006311,33.696283

In [22]:
podcast_data_order.to_csv('Data/Podcast_data_order.csv', index=True)

In [23]:
podcast_data_order.describe()

           # progam   # week day    # in hour         mean          std
count   1344.000000  1344.000000  1344.000000  1344.000000  1344.000000
mean   15625.000000  2232.142857   558.035714    64.487832    32.907744
std     2798.750697   431.806178   116.500130     2.664202     1.067797
min     9169.000000  1251.000000   274.000000    52.254230    28.651971
25%    13388.250000  1888.750000   471.000000    62.891472    32.179471
50%    15500.500000  2205.000000   545.000000    64.518748    32.869592
75%    17393.500000  2533.500000   637.000000    66.253130    33.613847
max    22847.000000  3521.000000   933.000000    72.439976    37.132306

In [24]:
podcast_Test_order = pd.DataFrame(columns=['Program','# progam','day','# week day','Time','# in hour','mean','std'])

In [25]:
podcast_Test_order

Empty DataFrame
Columns: [Program, # progam, day, # week day, Time, # in hour, mean, std]
Index: []

In [26]:
n=0
for podcast in Podcast_Test_df['Podcast_Name'].unique():
    podname_df = Podcast_Test_df[Podcast_Test_df['Podcast_Name'] == podcast]
    feature = podcast
    program_num = len(podname_df)
    
    for day in ['Sunday' ,'Monday' ,'Tuesday' ,'Wednesday','Thursday','Friday', 'Saturday']:
        try:
            pub_day_df = podname_df[podname_df['Publication_Day'] == day ]
            pod_day = day
            pod_day_num = len(pub_day_df)
        except:
            pub_day_df = podname_df
            pod_day = day
            pod_day_num = np.nan

        for hour in ['Night','Morning', 'Afternoon', 'Evening']:
            try:
                pub_hour_df = pub_day_df[pub_day_df['Publication_Time'] == hour ]
                time = hour
                time_num = len(pub_hour_df)
                mean = pub_hour_df['Episode_Length_minutes'].mean()
                std = pub_hour_df['Episode_Length_minutes'].std()
            except:
                pub_hour_df = pub_day_df
                time = hour
                time_num = np.nan
                mean = np.nan
                std = np.nan
                
            podcast_Test_order.loc[n] = [feature, program_num, pod_day, pod_day_num, time, time_num, mean, std]
            n = n +1
        n= n +4
    n=n +7

In [58]:
podcast_Test_order.describe()

          # progam   # week day    # in hour           mean           std
count  1344.000000  1344.000000  1344.000000    1344.000000  1.344000e+03
mean   5208.333333   744.047619   186.011905     429.549597  4.650056e+03
std     921.740515   144.738542    40.152018   13380.465482  1.692510e+05
min    3138.000000   421.000000    79.000000      50.031061  2.844882e+01
25%    4475.750000   636.000000   155.000000      62.248569  3.190707e+01
50%    5142.500000   725.000000   182.000000      64.584068  3.288597e+01
75%    5814.000000   854.750000   212.250000      66.850036  3.385007e+01
max    7553.000000  1145.000000   324.000000  490600.515188  6.204879e+06

In [59]:
podcast_Test_order

,Program,# progam,day,# week day,Time,# in hour,mean,std
0,Educational Nuggets,3963,Sunday,630,Night,149,65.795371,31.953644
1,Educational Nuggets,3963,Sunday,630,Morning,149,67.633185,34.922508
2,Educational Nuggets,3963,Sunday,630,Afternoon,158,63.944892,31.629876
3,Educational Nuggets,3963,Sunday,630,Evening,174,66.597139,33.073034
8,Educational Nuggets,3963,Monday,535,Night,154,66.694122,31.518004
...,...,...,...,...,...,...,...,...
3004,News Roundup,3138,Friday,449,Evening,143,60.293643,33.928964
3009,News Roundup,3138,Saturday,421,Night,120,66.440189,35.057697
3010,News Roundup,3138,Saturday,421,Morning,79,50.031061,32.115426
3011,News Roundup,3138,Saturday,421,Afternoon,102,62.486111,35.514188
3012,News Roundup,3138,Saturday,421,Evening,120,58.025179,33.941700

In [60]:
Podcast_Test_df.describe()

,id,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads
count,250000.000000,2.212640e+05,250000.000000,201168.000000,250000.000000
mean,874999.500000,4.192987e+02,59.716491,52.192796,1.355852
std,72168.927986,1.668545e+05,22.880028,28.445034,4.274399
min,750000.000000,2.470000e+00,2.490000,0.000000,0.000000
25%,812499.750000,3.578000e+01,39.250000,28.320000,0.000000
50%,874999.500000,6.397000e+01,59.900000,53.360000,1.000000
75%,937499.250000,9.415000e+01,79.390000,76.560000,2.000000
max,999999.000000,7.848626e+07,117.760000,116.820000,2063.000000

In [61]:
Podcast_Train_df.describe()

,id,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,750000.000000,662907.000000,750000.000000,603970.000000,749999.000000,750000.000000
mean,374999.500000,64.504738,59.859901,52.236449,1.348855,45.437406
std,216506.495284,32.969603,22.873098,28.451241,1.151130,27.138306
min,0.000000,0.000000,1.300000,0.000000,0.000000,0.000000
25%,187499.750000,35.730000,39.410000,28.380000,0.000000,23.178350
50%,374999.500000,63.840000,60.050000,53.580000,1.000000,43.379460
75%,562499.250000,94.070000,79.530000,76.600000,2.000000,64.811580
max,749999.000000,325.240000,119.460000,119.910000,103.910000,119.970000

In [27]:
# how many programs of more than 120 minutes
Podcast_Train_df[Podcast_Train_df['Episode_Length_minutes']>120]

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
74270,74270,Tech Trends,Episode 31,120.64,Technology,49.78,Saturday,Morning,50.54,1.0,Neutral,119.73000
87034,87034,Tech Talks,Episode 31,120.32,Technology,78.39,Thursday,Morning,54.64,1.0,Neutral,119.66000
101637,101637,Home & Living,Episode 16,325.24,Lifestyle,50.69,Tuesday,Afternoon,15.01,0.0,Positive,64.31981
168115,168115,Wellness Wave,Episode 78,120.64,Health,49.78,Thursday,Morning,50.54,1.0,Neutral,119.73000
473895,473895,Athlete's Arena,Episode 15,120.06,Sports,78.98,Saturday,Evening,56.64,1.0,Neutral,119.67000
516498,516498,Fashion Forward,Episode 81,120.37,Lifestyle,79.40,Thursday,Afternoon,54.66,0.0,Neutral,119.44000
552181,552181,Athlete's Arena,Episode 15,120.73,Sports,78.42,Friday,Evening,54.24,1.0,Neutral,119.67000
598106,598106,Crime Chronicles,Episode 53,120.93,True Crime,48.73,Friday,Morning,72.96,2.0,Positive,70.90288
688205,688205,Melody Mix,Episode 70,120.37,Music,76.45,Friday,Morning,54.74,1.0,Neutral,119.67000

In [65]:
Podcast_Test_df[Podcast_Test_df['Episode_Length_minutes']>120]

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
54434,804434,Current Affairs,Episode 36,7575.00,News,89.54,Saturday,Night,NaN,2.0,Negative
56597,806597,Market Masters,Episode 23,78486264.00,Business,55.45,Monday,Evening,48.50,0.0,Positive
72201,822201,Detective Diaries,Episode 81,120.37,True Crime,79.40,Thursday,Afternoon,NaN,0.0,Neutral
180050,930050,Tech Talks,Episode 23,120.73,Technology,50.27,Friday,Afternoon,60.43,0.0,Neutral

In [28]:
# How many programs Host_Popularity_percentage more than 99
Podcast_Train_df[Podcast_Train_df['Host_Popularity_percentage']>100]

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
23925,23925,Fitness First,Episode 79,93.17,Health,117.76,Sunday,Morning,67.73,2.0,Positive,81.23646
79078,79078,Current Affairs,Episode 17,107.24,News,118.73,Sunday,Evening,71.24,1.0,Positive,50.49238
111850,111850,Melody Mix,Episode 43,115.31,Music,105.57,Wednesday,Morning,52.25,0.0,Neutral,103.93098
113304,113304,Wellness Wave,Episode 67,35.35,Health,115.18,Sunday,Morning,1.63,0.0,Negative,30.61016
123611,123611,Finance Focus,Episode 86,34.18,Business,112.25,Wednesday,Morning,85.48,1.0,Positive,21.66793
132903,132903,Fashion Forward,Episode 50,64.04,Lifestyle,103.00,Monday,Evening,62.26,1.0,Positive,63.12551
170608,170608,Fashion Forward,Episode 55,64.03,Lifestyle,103.00,Monday,Evening,61.41,1.0,Positive,63.12551
176422,176422,Lifestyle Lounge,Episode 70,116.43,Lifestyle,117.14,Monday,Afternoon,71.48,1.0,Positive,109.62195
183757,183757,Fitness First,Episode 79,93.17,Health,117.76,Sunday,Morning,47.93,2.0,Positive,81.23646
187862,187862,True Crime Stories,Episode 86,34.17,True Crime,112.25,Friday,Morning,85.96,1.0,Positive,21.66793
206015,206015,Innovators,Episode 16,73.15,Technology,114.97,Wednesday,Morning,40.34,0.0,Negative,60.64154
222880,222880,Tech Trends,Episode 68,105.76,Technology,107.02,Friday,Morning,2.91,0.0,Neutral,83.09118
226171,226171,Comedy Corner,Episode 23,NaN,Comedy,118.69,Sunday,Morning,83.01,0.0,Positive,45.58000
321919,321919,Lifestyle Lounge,Episode 30,119.61,Lifestyle,117.14,Monday,Afternoon,71.52,1.0,Positive,109.62195
343982,343982,Current Affairs,Episode 17,56.03,News,118.93,Wednesday,Evening,94.40,1.0,Positive,50.49238
349735,349735,Lifestyle Lounge,Episode 41,105.71,Lifestyle,101.11,Sunday,Night,81.22,0.0,Neutral,75.06962
369147,369147,Lifestyle Lounge,Episode 90,119.61,Lifestyle,117.14,Monday,Evening,71.48,1.0,Positive,109.62195
459018,459018,Joke Junction,Episode 70,119.61,Comedy,117.14,Monday,Evening,71.52,1.0,Positive,109.62195
465407,465407,Tech Talks,Episode 16,34.50,Technology,109.38,Friday,Morning,67.74,0.0,Positive,7.07154
483248,483248,News Roundup,Episode 35,75.76,News,112.44,Thursday,Morning,52.28,1.0,Positive,74.16000
520995,520995,True Crime Stories,Episode 41,105.63,True Crime,101.31,Sunday,Night,40.41,0.0,Neutral,75.06962
534237,534237,Tune Time,Episode 34,109.98,Music,114.73,Tuesday,Morning,34.74,1.0,Neutral,74.64000
538582,538582,Mind & Body,Episode 31,68.56,Health,119.46,Monday,Afternoon,90.07,0.0,Negative,63.29195
568996,568996,Joke Junction,Episode 10,116.60,Comedy,104.60,Sunday,Morning,87.73,0.0,Positive,104.87153
599478,599478,Lifestyle Lounge,Episode 15,117.26,Lifestyle,117.14,Monday,Afternoon,71.48,1.0,Positive,109.62195

In [30]:
Podcast_Test_df[Podcast_Test_df['Host_Popularity_percentage']>100]

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
59446,809446,Detective Diaries,Episode 47,71.98,True Crime,103.00,Monday,Evening,62.26,1.0,Positive
70250,820250,Lifestyle Lounge,Episode 41,105.71,Lifestyle,101.31,Sunday,Night,81.22,0.0,Neutral
88169,838169,World Watch,Episode 67,39.72,News,115.18,Friday,Morning,1.63,0.0,Negative
90886,840886,Fitness First,Episode 79,93.17,Health,117.76,Saturday,Morning,57.08,2.0,Positive
106857,856857,Detective Diaries,Episode 10,112.80,True Crime,104.60,Sunday,Evening,87.13,0.0,Positive
108106,858106,Detective Diaries,Episode 71,105.51,True Crime,101.31,Sunday,Morning,81.11,0.0,Neutral
124250,874250,Current Affairs,Episode 69,55.06,News,104.60,Monday,Night,5.63,2.0,Positive
127620,877620,Detective Diaries,Episode 50,65.09,True Crime,103.00,Monday,Evening,84.43,1.0,Positive
143693,893693,World Watch,Episode 78,10.71,News,114.93,Sunday,Afternoon,90.15,0.0,Positive
180528,930528,News Roundup,Episode 64,103.11,News,107.76,Friday,Evening,22.71,1.0,Neutral
183787,933787,Fashion Forward,Episode 50,64.03,Lifestyle,103.00,Monday,Evening,61.41,1.0,Positive
186742,936742,Educational Nuggets,Episode 45,116.60,Education,117.14,Monday,Evening,71.48,1.0,Positive

In [32]:
# How many programs Guest_Popularity_percentage more than 99.99
Podcast_Train_df[Podcast_Train_df['Guest_Popularity_percentage']>100]

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
6770,6770,Tune Time,Episode 85,NaN,Music,73.54,Wednesday,Night,107.08,0.0,Positive,35.25323
32435,32435,World Watch,Episode 44,10.94,News,35.98,Thursday,Afternoon,114.72,0.0,Negative,1.62509
86967,86967,Tune Time,Episode 68,35.62,Music,27.20,Monday,Night,106.90,0.0,Positive,32.97339
106804,106804,Tune Time,Episode 79,45.36,Music,58.79,Monday,Evening,110.14,2.0,Negative,31.53171
118315,118315,Style Guide,Episode 32,80.30,Lifestyle,29.95,Wednesday,Afternoon,102.13,1.0,Negative,54.73758
149146,149146,Laugh Line,Episode 21,92.27,Comedy,88.98,Wednesday,Night,105.48,1.0,Positive,44.11321
194629,194629,Tune Time,Episode 85,NaN,Music,87.53,Wednesday,Night,107.81,0.0,Positive,35.25323
202865,202865,Athlete's Arena,Episode 19,7.30,Sports,75.26,Thursday,Afternoon,114.72,2.0,Negative,1.62509
253381,253381,Innovators,Episode 44,NaN,Technology,45.70,Sunday,Night,119.91,0.0,Negative,48.40501
259197,259197,Educational Nuggets,Episode 76,55.02,Education,69.43,Tuesday,Morning,115.62,2.0,Positive,41.35534
291133,291133,Athlete's Arena,Episode 85,115.16,Sports,57.84,Saturday,Night,102.38,0.0,Positive,89.10949
301452,301452,Lifestyle Lounge,Episode 15,NaN,Lifestyle,67.09,Tuesday,Night,114.88,1.0,Neutral,52.94702
377317,377317,Educational Nuggets,Episode 76,55.02,Education,69.43,Tuesday,Morning,115.43,2.0,Positive,41.35534
471451,471451,Educational Nuggets,Episode 76,48.58,Education,69.43,Tuesday,Morning,115.41,0.0,Positive,41.35534
489091,489091,Mystery Matters,Episode 13,37.85,True Crime,27.17,Monday,Night,107.34,0.0,Positive,32.97339
510609,510609,Tune Time,Episode 85,NaN,Music,63.89,Wednesday,Night,107.81,0.0,Positive,35.25323
654247,654247,Educational Nuggets,Episode 76,55.02,Education,69.43,Tuesday,Morning,115.62,0.0,Positive,41.35534
720528,720528,Music Matters,Episode 60,13.32,Music,33.18,Wednesday,Afternoon,107.58,0.0,Negative,13.03243
723350,723350,Gadget Geek,Episode 59,63.02,Technology,75.91,Sunday,Night,105.44,1.0,Positive,39.89589

In [34]:
Podcast_Test_df[Podcast_Test_df['Guest_Popularity_percentage']>100]

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
78898,828898,Detective Diaries,Episode 61,24.29,True Crime,80.60,Friday,Night,116.32,1.0,Neutral
121878,871878,Humor Hub,Episode 28,99.32,Comedy,81.54,Monday,Evening,116.82,1.0,Positive
192155,942155,Tune Time,Episode 48,102.89,Music,90.38,Monday,Night,107.21,1.0,Positive
199455,949455,Educational Nuggets,Episode 76,55.82,Education,69.43,Tuesday,Morning,115.85,2.0,Positive
211582,961582,Humor Hub,Episode 28,80.33,Comedy,71.52,Monday,Evening,116.82,1.0,Positive

In [29]:
len(Podcast_Train_df[Podcast_Train_df['Host_Popularity_percentage']>100])

25

In [31]:
len(Podcast_Test_df[Podcast_Test_df['Host_Popularity_percentage']>100])

12

In [33]:
len(Podcast_Train_df[Podcast_Train_df['Guest_Popularity_percentage']>100])

19

In [35]:
len(Podcast_Test_df[Podcast_Test_df['Guest_Popularity_percentage']>100])

5